apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miratech.ma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USER/k8s-windows-lab.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true