# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miratech
  labels:
    app: miratech
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: miratech
  template:
    metadata:
      labels:
        app: miratech
    spec:
      containers:
        - name: nginx
          image: ghcr.io/cherqi98/miratech:20251225-b04bf07
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: miratech-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: miratech